def get_blr_assembly_constituency_name(e):
    ac_names = {
        "150": "Yelahanka",
        "151": "Krishnarajapuram",
        "152": "Byatarayanapura",
        "153": "Yeshwantpur",
        "154": "Rajarajeshwarinagar",
        "155": "Dasarahalli",
        "156": "Mahalakshmi Layout",
        "157": "Malleshwaram",
        "158": "Hebbal",
        "159": "Pulakeshinagar",
        "160": "Sarvagnanagar",
        "161": "C. V. Raman Nagar",
        "162": "Shivajinagar",
        "163": "Shanti Nagar",
        "164": "Gandhi Nagar",
        "165": "Rajaji Nagar",
        "166": "Govindraj Nagar",
        "167": "Vijay Nagar",
        "168": "Chamrajpet",
        "169": "Chickpet",
        "170": "Basavanagudi",
        "171": "Padmanabhanagar",
        "172": "B. T. M. Layout",
        "173": "Jayanagar",
        "174": "Mahadevapura",
        "175": "Bommanahalli",
        "176": "Bangalore South",
        "177": "Anekal",
        "178": "Hoskote",
        "179": "Devanahalli",
        "180": "Doddaballapur",
        "181": "Nelamangala",
        "182": "Magadi",
        "183": "Ramanagaram",
        "184": "Kanakapura",
        "185": "Channapatna",
        "ca_0": "Other Assemblies"
    }

    return ac_names.get(e, "")